name: sse_channel
description: StreamChannel wrappers for Server Sent Events.
version: 0.0.3
repository: https://www.github.com/jamiewest/sse_channel

environment:
  sdk: ">=2.18.4 <4.0.0"

dependencies:
  async: ^2.10.0
  http: ^1.1.0
  pool: ^1.5.1
  sse: ^4.1.3
  stream_channel: ^2.1.1
  uuid: ^4.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
